apiVersion: v1
kind: ConfigMap
metadata:
  name: llama-stack-config
data:
  run.yaml: |
    # Llama Stack Configuration
    version: '2'
    image_name: starter
    apis:
    - inference
    providers:
      inference:
      - provider_id: ollama
        provider_type: "remote::ollama"
        config:
          url: "http://ollama-server-service.ollama-dist.svc.cluster.local:11434"
    models:
      - model_id: "llama3.2:1b"
        provider_id: ollama
        model_type: llm
    server:
      port: 8321
---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: llamastack-with-userconfig
spec:
  replicas: 1
  server:
    distribution:
      name: starter
    containerSpec:
      port: 8321
      env:
      - name: OLLAMA_EMBEDDING_MODEL
        value: all-minilm:l6-v2
    userConfig:
      configMapName: llama-stack-config
      # configMapNamespace: ""  # Optional - defaults to the same namespace as the CR
